In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#Voc size
voc_size=1000

In [7]:
## One hot encoding
##we can pass single word or whole sentence
one_hot_repr=[one_hot(words,voc_size) for words in sent] 
one_hot_repr

[[974, 670, 701, 236],
 [974, 670, 701, 223],
 [974, 606, 701, 830],
 [22, 263, 293, 800, 448],
 [22, 263, 293, 800, 486],
 [894, 974, 126, 701, 484],
 [483, 444, 422, 800]]

In [8]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [15]:
sent_len=max([len(i.split()) for i in sent])
sent_len
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[  0 974 670 701 236]
 [  0 974 670 701 223]
 [  0 974 606 701 830]
 [ 22 263 293 800 448]
 [ 22 263 293 800 486]
 [894 974 126 701 484]
 [  0 483 444 422 800]]


In [16]:
# we have padded the input senetences to get same lenth for all inputs
#lets create the model
model=Sequential()
model.add(Embedding(voc_size,output_dim=10,input_length=sent_len))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)[0][0:4] ##each word into ten vectors

1/1 [==============================] - 0s 35ms/step


array([[ 0.00405069,  0.00246241,  0.01174815,  0.04555297,  0.0493757 ,
         0.02437265,  0.01763259,  0.02144896,  0.00029894, -0.01977296],
       [ 0.02862394,  0.00919323, -0.0306057 , -0.03836051,  0.0260384 ,
        -0.04159646, -0.03885936,  0.03317754, -0.03403022, -0.04703573],
       [ 0.0477859 ,  0.03735484, -0.04734905,  0.04936278,  0.04182256,
        -0.0461758 , -0.03246345, -0.04833436,  0.04034435, -0.04566294],
       [-0.01087616,  0.0054187 ,  0.0379208 ,  0.00836737, -0.0006173 ,
         0.02307067, -0.01361718, -0.03676618, -0.0291062 ,  0.01863131]],
      dtype=float32)